price360/urls.py
from django.conf.urls import url

from price360.views import index, category, change_shop, move_products, export, CategoryListView, import_step_1, \
    import_step_2, import_step_3, import_step_4, CategoryCreateView, CategoryUpdateView

from price360.import_views.evrosvet import evrosvet_import_step_1, evrosvet_import_step_2

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^change_shop/(?P<shop_id>[0-9])/$', change_shop, name='change-shop'),

    url(r'^category/$', CategoryListView.as_view(), name='settings-category-list'),
    url(r'^category/create/$', CategoryCreateView.as_view(), name='settings-category-create'),
    url(r'^category/(?P<pk>[0-9])/$', CategoryUpdateView.as_view(), name='settings-category-update'),

    url(r'^products/category/(?P<category_id>[0-9])/$', category, name='category'),
    url(r'^products/move/$', move_products, name='move-products'),
    url(r'^products/export/(?P<category_id>[0-9])/$', export, name='export'),

    url(r'^products/import/$', import_step_1, name='import-step-1'),
    url(r'^products/import/step/2/$', import_step_2, name='import-step-2'),
    url(r'^products/import/step/3/$', import_step_3, name='import-step-3'),
    url(r'^products/import/step/4/$', import_step_4, name='import-step-4'),

    url(r'^products/import_evrosvet/$', evrosvet_import_step_1, name='import-evrosvet-step-1'),
    url(r'^products/import_evrosvet/step/2/$', evrosvet_import_step_2, name='import-evrosvet-step-2'),

]

project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve
from accounts.views import login_view, logout_view


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', login_view, name='login'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'', include('price360.urls')),
]

if settings.DEBUG:
    urlpatterns += (url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),)

    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

price360/models.py
from os import uname_result

from django.db import models
from django.contrib.postgres.fields import JSONField, IntegerRangeField
from mptt.models import MPTTModel, TreeForeignKey, TreeManager
from model_utils.models import TimeStampedModel
from dirtyfields import DirtyFieldsMixin

from currency.models import Currency
from price360.filter_field import TypeBool, TypeFloat, TypeInt, TypeString


class FieldQuerySet(models.QuerySet):
    def active(self):
        return self.filter(is_active=True)

    def in_filter(self):
        return self.filter(show_in_filter=True)


class Shop(DirtyFieldsMixin, TimeStampedModel, models.Model):
    code = models.CharField("Код", max_length=50, blank=False)
    name = models.CharField("Название", max_length=200, blank=False)
    is_active = models.BooleanField("Активность", default=True)

    class Meta:
        verbose_name = "Магазин"
        verbose_name_plural = "Магазины"

    def __str__(self):
        return "{} ({})".format(self.name, self.code)


class ImportResult(DirtyFieldsMixin, TimeStampedModel, models.Model):
    IMPORT_EVROSVET = "evrosvet"

    IMPORT_LIST = (
        (IMPORT_EVROSVET, 'Evrosvet'),
    )

    filename = models.CharField("Имя файла", max_length=200, blank=False)
    rows = models.PositiveIntegerField("Кол-во товаров", blank=False)
    success_rows = models.PositiveIntegerField("Кол-во обработанных товаров", blank=False)
    user = models.ForeignKey("accounts.User", verbose_name="Пользователь", blank=False)
    shop = models.ForeignKey(Shop, verbose_name="Магазин")
    import_price = models.CharField("Название", choices=IMPORT_LIST, null=True, max_length=50)

    class Meta:
        verbose_name = "Импорт"
        verbose_name_plural = "Импорты"

    def __str__(self):
        return "{} в {} ({})".format(self.filename, self.created, self.user)


class Manufacturer(DirtyFieldsMixin, TimeStampedModel, models.Model):
    name = models.CharField("Название", max_length=200, blank=False)

    class Meta:
        verbose_name = "Производитель"
        verbose_name_plural = "Производители"

    def __str__(self):
        return self.name


class Category(DirtyFieldsMixin, TimeStampedModel, MPTTModel):
    name = models.CharField("Название", max_length=250)
    parent = TreeForeignKey('self', verbose_name='Родительская категория', null=True, blank=True,
                            related_name='children', db_index=True)
    shop = models.ForeignKey(Shop, verbose_name="Магазин")

    # objects = TreeManager()

    class MPTTMeta:
        order_insertion_by = ['name']

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return "{} ({})".format(self.name, self.shop.code)


class Field(DirtyFieldsMixin, models.Model):
    TYPE_STR = 'string'
    TYPE_INT = 'int'
    TYPE_FLOAT = 'float'
    TYPE_BOOL = 'bool'
    TYPES_LIST = (
        (TYPE_STR, 'String'),
        (TYPE_INT, 'Integer'),
        (TYPE_FLOAT, 'Float'),
        (TYPE_BOOL, 'Boolean'),
    )
    TYPES_CONVERT = {
        TYPE_STR: TypeString,
        TYPE_INT: TypeInt,
        TYPE_FLOAT: TypeFloat,
        TYPE_BOOL: TypeBool,
    }

    code = models.CharField("Код поля", max_length=100, blank=False, unique=True)
    name = models.CharField("Название", max_length=100, blank=False)
    category = TreeForeignKey(Category, verbose_name="Категория", related_name='fields')
    field_type = models.CharField("Тип", max_length=50, choices=TYPES_LIST, null=False, blank=False)
    many = models.BooleanField("Множественное", default=False)
    required = models.BooleanField("Обязательное", default=False)
    show_in_filter = models.BooleanField("Показывать в фильтре", default=True)
    prefix = models.CharField("Префикс", max_length=50, blank=True)
    postfix = models.CharField("Постфикс", max_length=50, blank=True)
    is_active = models.BooleanField("Активность", default=True)
    sort = models.PositiveIntegerField("Сортировка", default=500)

    objects = FieldQuerySet.as_manager()

    class Meta:
        ordering = ['sort']
        verbose_name = "Поле"
        verbose_name_plural = "Поля"

    def __str__(self):
        return "{} ({})".format(self.name, self.code)

    def get_converter(self):
        return Field.TYPES_CONVERT[self.field_type]


class FilterFieldValue(TimeStampedModel, models.Model):
    field = models.OneToOneField(Field, verbose_name="Поле", unique=True)
    values = JSONField("Значения", default=[])

    class Meta:
        verbose_name = "Значение поля (фильтр)"
        verbose_name_plural = "Значения поля (фильтр)"

    def __str__(self):
        return "{}".format(self.field)


class Product(DirtyFieldsMixin, TimeStampedModel, models.Model):
    STOCK_YES = 'yes'
    STOCK_NO = 'no'
    STOCK_LIST = (
        (STOCK_YES, 'Да'),
        (STOCK_NO, 'Нет'),
    )
    code = models.CharField("Код", max_length=50)
    name = models.CharField("Название", max_length=250)
    category = TreeForeignKey(Category, verbose_name="Категория")
    manufacturer = models.ForeignKey(Manufacturer, verbose_name="Производитель")
    wholesale_price = models.DecimalField("Опт. цена", max_digits=8, decimal_places=2)
    wholesale_currency = models.ForeignKey(Currency, verbose_name='Валюта (опт.)',
                                           related_name='product_wholesale_currency')
    retail_price = models.DecimalField("Розн. цена", max_digits=8, decimal_places=2)
    retail_currency = models.ForeignKey(Currency, verbose_name='Валюта (розн.)', related_name='product_retail_currency')
    stock_raw = models.CharField("Наличие (RAW)", max_length=100, blank=True, editable=False)
    stock = models.CharField("Наличие", max_length=10, choices=STOCK_LIST, db_index=True)
    stock_num = IntegerRangeField("Наличие (кол-во)", blank=True)
    guarantee = models.PositiveSmallIntegerField("Гарантия (мес.)", blank=True)
    info = models.TextField("Доп. информация", blank=True)
    prices = JSONField(verbose_name="Доп. цены", blank=True, null=True)
    fields = JSONField(verbose_name="Доп. поля", blank=True, null=True)
    import_result = models.ForeignKey(ImportResult, verbose_name="Импорт")

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"

    def __str__(self):
        return "#{} {}".format(self.code, self.name)


class ImportCategory(DirtyFieldsMixin, TimeStampedModel, models.Model):
    import_result = models.ForeignKey(ImportResult, verbose_name="Импорт")
    name = models.CharField("Название", max_length=250)
    shop = models.ForeignKey(Shop, verbose_name="Магазин")

    class Meta:
        verbose_name = "Импорт категория"
        verbose_name_plural = "Импорт категории"

    def __str__(self):
        return "{} ({})".format(self.name, self.shop.code)


class ImportManufacturer(DirtyFieldsMixin, TimeStampedModel, models.Model):
    name = models.CharField("Название", max_length=200, blank=False)

    class Meta:
        verbose_name = "Импорт производитель"
        verbose_name_plural = "Импорт производители"

    def __str__(self):
        return self.name


class ImportProduct(DirtyFieldsMixin, TimeStampedModel, models.Model):
    STOCK_YES = 'yes'
    STOCK_NO = 'no'
    STOCK_LIST = (
        (STOCK_YES, 'Да'),
        (STOCK_NO, 'Нет'),
    )
    code = models.CharField("Код", max_length=50)
    name = models.CharField("Название", max_length=250)
    category = TreeForeignKey(ImportCategory, verbose_name="Импорт категория")
    manufacturer = models.ForeignKey(ImportManufacturer, verbose_name="Производитель")
    wholesale_price = models.DecimalField("Опт. цена", max_digits=8, decimal_places=2)
    wholesale_currency = models.ForeignKey(Currency, verbose_name='Валюта (опт.)',
                                           related_name='import_product_wholesale_currency')
    retail_price = models.DecimalField("Розн. цена", max_digits=8, decimal_places=2)
    retail_currency = models.ForeignKey(Currency, verbose_name='Валюта (розн.)',
                                        related_name='import_product_retail_currency')
    stock_raw = models.CharField("Наличие (RAW)", max_length=100, blank=True, editable=False)
    stock = models.CharField("Наличие", max_length=10, choices=STOCK_LIST, db_index=True)
    stock_num = IntegerRangeField("Наличие (кол-во)", blank=True)
    guarantee = models.PositiveSmallIntegerField("Гарантия (мес.)", blank=True)
    info = models.TextField("Доп. информация", blank=True)
    prices = JSONField(verbose_name="Доп. цены", blank=True, null=True)
    fields = JSONField(verbose_name="Доп. поля", blank=True, null=True)
    import_result = models.ForeignKey(ImportResult, verbose_name="Импорт")

    class Meta:
        verbose_name = "Импорт товар"
        verbose_name_plural = "Импорт товары"

    def __str__(self):
        return "#{} {}".format(self.code, self.name)

price360/forms.py
from django import forms
from mptt.forms import TreeNodeChoiceField

from price360.models import Category, Currency, Manufacturer


class ImportStep1Form(forms.Form):
    file = forms.FileField(label="Excel файл")


class ImportStep2Form(forms.Form):
    sheet = forms.ChoiceField(label="Страница")
    category = TreeNodeChoiceField(queryset=Category.objects.all(), label="Категория")

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)  # TODO: Need check if None
        sheets = kwargs.pop('sheets', [])
        super().__init__(*args, **kwargs)
        # self.fields['category'].queryset = Category.objects.filter(shop=user.last_shop).all()
        self.fields['sheet'].choices = sheets
        self.fields['category'].queryset = Category.objects.filter(shop=user.last_shop).all()


class ImportStep3Form(forms.Form):
    wholesale_currency = forms.ModelChoiceField(queryset=Currency.objects.all(), label="Опт. валюта")
    retail_currency = forms.ModelChoiceField(queryset=Currency.objects.all(), label="Розн. валюта")
    manufacturer = forms.ModelChoiceField(queryset=Manufacturer.objects.all(), label="Производитель")
    guarantee = forms.CharField(label="Гарантия (мес.)")

templates/price360/product/category.html
{% extends 'layouts/main.html' %}
{% load product_tags %}
{% load widget_tweaks %}
{% load mptt_tags %}
{% load bootstrap_pagination %}

{% block page_name %}
    Товары
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box box-default">
                <div class="box-header with-border">
                    <h3 class="box-title">Фильтр</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse"><i
                                class="fa fa-minus"></i>
                        </button>
                    </div>
                </div>
                <div class="box-body" style="display: block;">
                    <form>
                        <form action="" method="get">
                            <div class="row">
                                <div class="col-md-2">
                                    <label for="id_code">{{ filter.form.code.label }}:</label>
                                    {{ filter.form.code|add_class:'form-control' }}
                                </div>
                                <div class="col-md-2">
                                    <label for="id_name">{{ filter.form.name.label }}:</label>
                                    {{ filter.form.name|add_class:'form-control' }}
                                </div>
                                <div class="col-md-2">
                                    <label for="id_in_stock">{{ filter.form.in_stock.label }}:</label>
                                    {{ filter.form.in_stock|add_class:'form-control' }}
                                </div>
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-md-12">
                                  <div class="box box-default">
                                      <div class="box-header with-border">
                                          <h3 class="box-title">Фильтр по полям</h3>
                                      </div>
                                      <div class="box-body">
                                          {% for field in filter.form %}
                                              {% if 'json' in field.name %}
                                                  <div class="col-md-2">
                                                      <label for="{{ field.auto_id }}">{{ field.label }}:</label>
                                                      {{ field|add_class:'form-control' }}
                                                  </div>
                                              {% endif %}
                                          {% endfor %}
                                      </div>
                                  </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary">Применить</button>
                        </form>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Товары в категории "{{ category }}"</h3>
                    <div class="box-tools">
                        <form method="GET" action="">
                            {% for field, value in filter_query_fields.items %}
                                <input type="hidden" name="{{ field }}" value="{{ value }}">
                            {% endfor %}
                            <div class="input-group input-group-sm" style="width: 160px; float: left; margin-right: 10px">
                                <label for="id_wholesale_currency">Опт. цена:</label>
                                <select id="id_wholesale_currency" name="wholesale_currency_display" class="form-control pull-right" style="width: 80px">
                                    <option disabled selected>Валюта</option>
                                    {% for currency in currencies %}
                                        <option value="{{ currency.code }}" {% if currency.code == wholesale_currency_display %}selected{% endif %}>
                                            {{ currency }}
                                        </option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="input-group input-group-sm" style="width: 160px; float: left;  margin-right: 10px">
                                <label for="id_retail_currency">Розн. цена:</label>
                                <select id="id_retail_currency" name="retail_currency_display" class="form-control pull-right" style="width: 80px">
                                    <option disabled selected>Валюта</option>
                                    {% for currency in currencies %}
                                        <option value="{{ currency.code }}" {% if currency.code == retail_currency_display %}selected{% endif %}>
                                             {{ currency }}
                                        </option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="input-group input-group-sm" style="width: 80px;">
                                <button class="btn btn-primary">Применить</button>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <form method="POST" action="/products/move/">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-3">
                                Перенести выбранные товары в:
                            </div>
                            <div class="col-md-3">
                                <select class="form-control" name="category_id">
                                    <option disabled selected>-- Выберите категорию --</option>
                                    {% for category,structure in categories|tree_info %}
                                        <option value="{{ category.pk }}">
                                        {% category_level category.level %} {{ category.name }}
                                        </option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="col-md-2">
                                <button class="btn btn-success" id="move-button" disabled>Перенести</button>
                            </div>
                            <div class="col-md-2">
                                <a class="btn btn-info" href="{% url 'export' category.pk %}">
                                    <i class="fa fa-download"></i> Экспорт
                                </a>
                            </div>
                        </div>
                        <br>
                        <table class="table table-bordered table-hover">
                            <tr>
                                <th></th>
                                <th>Артикул</th>
                                <th>Название</th>
                                <th>Производитель</th>
                                <th>Опт. цена</th>
                                <th>Розн. цена</th>
                                <th>Наличие</th>
                                {% for field in category_fields %}
                                    <th>{{ field.name }}</th>
                                {% endfor %}
                            </tr>
                            {% for product in products %}
                                <tr>
                                    <td><input type="checkbox" class="product-checkbox" name="product_selected" value="{{ product.pk }}"></td>
                                    <td>{{ product.code }}</td>
                                    <td>{{ product.name }}</td>
                                    <td>{{ product.manufacturer }}</td>
                                    <td>
                                        {% show_price product 'wholesale' wholesale_currency_display currency_cache currency_rate_cache %}
                                    </td>
                                    <td>
                                        {% show_price product 'retail' retail_currency_display currency_cache currency_rate_cache %}
                                    </td>
                                    <td>
                                        {% if product.stock_num %}
                                            {{ product.stock_num.lower }}-{{ product.stock_num.upper }}
                                        {% elif product.stock %}
                                            {% if product.stock == 'yes' %}
                                                Да
                                            {% elif product.stock == 'no' %}
                                                Нет
                                            {% endif %}
                                        {% else %}
                                            -
                                        {% endif %}
                                    </td>
                                    {% for field in category_fields %}
                                        <td>{% product_tags product.fields field.code %}</td>
                                    {% endfor %}
                                </tr>
                            {% endfor %}
                        </table>
                        {% bootstrap_paginate products %}
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript_bottom %}
    <script>
        $(document).ready(function() {
            $('.product-checkbox').on('change', function(){
                var checked = $('.product-checkbox:checked').length;
                if (checked > 0) {
                    $('#move-button').attr('disabled', false);
                } else {
                    $('#move-button').attr('disabled', true);
                }
            })
        })
    </script>
{% endblock %}